repo: "typographic-insets"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - css

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    has:
      - ["figure"]
      - ["figcaption"]
      - ["blockquote"]
    search:
      - "::first-letter"
      - "float: left"
      - "float: right"

screenshots:
  - path: "index.html"
    sizes: [1400]
